### ISSUE TITLE
x64 only. (Needs to work on my 32Bit Computer.)

### ISSUE THREAD

**Issue by YuzuMSX** [sin2000/zdownloader#11]
I have serval issues.
- My computer is x86 Win7 Celeron
- This software don't run because is x64 only.

I don't have a working x64 computer because This computer become expensive for today.

So I don't have a choice to build for Old x86 computers but there's any alternatives to Python scripts.

**Comment by sin2000** [comment]
I have added 32 bit zdownloader release for Windows:
https://github.com/sin2000/zdownloader/releases/download/1.9/win7_8_10-x86.zip
