### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by keefetang** [sin2000/zdownloader#12]
Hi, is there any plans to support MacOS?

**Comment by sin2000** [comment]
~~I don't have MacOS, so I can't compile the zdownloader for this system.~~
But you can try compile it by yourself from source code.
I will help if you run into problems with compiling the program.

**Comment by sin2000** [comment]
@keefetang I have added MacOS support in commits https://github.com/sin2000/zdownloader/commit/fc26b7c96b548f9068256edd205660a16537117b https://github.com/sin2000/zdownloader/commit/914238d93c7de1e1270fea3bf8b5c4fcb8b53551
You can also download precomiled binaries from https://github.com/sin2000/zdownloader/releases/download/2.0/macos_x64.tgz
How to run zdownloader on MacOS? See updated README: https://github.com/sin2000/zdownloader/blob/master/README.md
