### ISSUE TITLE
No filename in Content & QNetworkReplyImplPrivate::error: Internal problem

### ISSUE THREAD

**Issue by shadow443** [sin2000/zdownloader#15]
Hi, I can't download links from google drive. I get the following messages:

> [20200520.06:17:31][D] Restarting download link info. Error: No filename in Content-Disposition header
> [20200520.06:17:31][W] QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
> [20200520.06:17:31][D] abort: https://doc-08-7o-docs.googleusercontent.com/docs/securesc/ha0ro************
> [20200520.06:17:31][D] **Restarting download link info. Error: No filename in Content-Disposition** header
> [20200520.06:17:31][W] **QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.**

What I did:
Download and unzip linux-x86-64.zip, create links.txt and run ./start_zd.sh

I thought it was a google api problem, so I followed the steps here [HOWTO_gdrive_service_account](https://github.com/sin2000/zdownloader/blob/master/HOWTO_gdrive_service_account.md)  and I downloaded the json and set it to zdownloader.ini but I get the same results.

My links.txt file contains google drive links in this format: https://drive.google.com/file/d/1ASiJ******

I am using version 2.0 linux-x86-64.zip in a vps (kernel: 4.15.0-99-generic, Ubuntu 18.04.4 LTS)

What could be causing these errors? How can I know if I have the requirements to run zdownloader? Thanks

**Comment by sin2000** [comment]
> [W] QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.

@shadow443 This is warning from Qt and it is harmless. Qt issue: https://bugreports.qt.io/browse/QTBUG-36127. I will probably hide this warning message in next version of zdownloader.

> [20200520.06:17:31][D] Restarting download link info. Error: No filename in Content-Disposition header

@shadow443 This message indicating that zdownloader is not using gdrive api.
Did you set `use_gdrive_api` variable value to `true` (in [zdownloader.ini](https://github.com/sin2000/zdownloader/blob/master/src/zdownloader/data/zdownloader.ini)  file)?

**Comment by shadow443** [comment]
> This message indicating that zdownloader is not using gdrive api.
Did you set use_gdrive_api variable value to true (in zdownloader.ini file)?

@sin2000  That fixed it. It was a rookie mistake . Thanks
