### ISSUE TITLE
Could not open file for write&read: ~/downloads/filename.part

### ISSUE THREAD

**Issue by auspic7** [sin2000/zdownloader#16]
WSL, Ubuntu 20.04 LTS

permission of the directory:
`drwxrwxrwx  2 auspic7 auspic7 4.0K Jul 12 14:10 downloads`

starting the program with command `sudo ./start_zd.sh` did not work.
[D] Could not open file for write&read: ~/downloads/filename.part

what should i do to resolve the error?

**Comment by auspic7** [comment]
`download_directory=.`
fixed this problem. but I wonder why the error occured.

**Comment by sin2000** [comment]
Hello,

@auspic7 you can't use tilde (~) character in directory or file paths in zdownloader configuration. Zdownloader does not understand tilde character like system shell (eg. `bash`).
However, you can use absolute paths (eg. `/home/user/downloads`) or relative paths (eg. `../../downloads`).

**Comment by auspic7** [comment]
ohh I see. I think we can make the program understand the ~ character on the paths then. or you can add the comments describing that you cannot use the symbol in paths

**Comment by auspic7** [comment]
also IMHO the error message 'Could not open file for write&read:' is quite ambiguous. in the situation that it cannot parse a path, it should print the error message that says it cannot parse the path string

**Comment by sin2000** [comment]
There is little misunderstanding. You can use tilde (~) character in `download_directory=` but tilde character in this case is directory name (that is, you can create directory ~, eg.: `mkdir '~'`). So ~ character in zdownloader **is not** an alias to user's home directory.

> also IMHO the error message 'Could not open file for write&read:' is quite ambiguous. in the situation that it cannot parse a path, it should print the error message that says it cannot parse the path string

No, it can parse a path, but in your case '~' directory does not exists, so zdownloader cannot open file.

I will update the README.md file as follows: you cannot use tilde(~) character as alias to user's home directory.

**Comment by sin2000** [comment]
I have updated README.md: 04b522473239cd2554d6adc61b0c68eb99d83bef
