### ISSUE TITLE
Qt_5.15 not found

### ISSUE THREAD

**Issue by shadow443** [sin2000/zdownloader#17]
Hello I wanted to try version 2.1 but I have this when starting ./start_zd.sh:
- /lib/libQt5Core.so.5: version` Qt_5.15 'not found (required by ./zdownloader) 

I tried to compile it but I don't have much experience with Qt.
libQt5Core.so.5 is in "../lib" but it doesn't seem to be the correct version.

**Comment by shadow443** [comment]
I also tried it in an instance of aws:

unzip linux-x86-64.zip
chmod + x start_zd.sh zdownloader
./start_zd.sh

I get the same error.

**Comment by ghost** [comment]
Ubuntu 18

**Comment by shadow443** [comment]
Ubuntu 18.04 in vps.

**Comment by shadow443** [comment]
Ubuntu 18.04

**Comment by sin2000** [comment]
@shadow443 Thank you for reporting this.
Looks like zdownloader linux binaries was shipped with Qt 5.14 by mistake.
**I have updated linux binaries.**
 
> I tried to compile it but I don't have much experience with Qt.
> libQt5Core.so.5 is in "../lib" but it doesn't seem to be the correct version.

In this case you don't need to compile Qt or zdownloader by itself. You can always grab newest precompiled qt libraries from qt official site.
