### ISSUE TITLE
Considerably slower than chrome is.

### ISSUE THREAD

**Issue by zaphod77** [sin2000/zdownloader#20]
If i use chrome to download the files from zippyshare, 500 megs generally downloads in less than a minute.

This program takes 4-5 minutes to do the same.

How do I fix this?

**Comment by sin2000** [comment]
Hello,
Please provide more details:
1. What OS do you use?
2. What is the maximum download speed of your Internet connection?
3. Could you please send me zippyshare link(s) that you are using for the test?
4. Please send me also **applog_*** file(s) and **zdownloader.ini** settings file from zdownloader.

If you like you can send me links and logs to e-mail: pawniz at onet.pl

**Comment by zaphod77** [comment]
1) i use windows 10.
2) Internet speed test
015102050100+
164.2
Megabits per second
Testing upload...

169.5

Mbps download

164.2

Mbps upload
Latency: 18 ms
Server: Chicago

Your Internet connection is very fast.

Your Internet connection should be able to handle multiple devices
streaming HD videos, video conferencing, and gaming at the same time.

3) any zippyshare link with a large file is suitable for testing. I'm
having difficulty finding one i can actually share, but you should have no
trouble locating a 500MB rar file or two to download for a test.

4)  a snippet, showing typical results with the downloader.
[20210301.08:41:56][D] SPEED: 12.74 AVG SPEED: 15.66 Mb/s
[20210301.08:41:58][D] Progress: 3.52% [17.61/500.00MB] ETA: 4m50s ActSeg:
1/1 - xxxx.rar
.
(snip)
.
[20210301.08:45:56][D] SPEED: 15.89 AVG SPEED: 15.85 Mb/s
[20210301.08:45:58][D] Progress: 99.52% [497.61/500.00MB] ETA: 1s ActSeg:
1/1 - xxxx.rar
[20210301.08:45:58][D] HTTP: xxxx.rar from
https://www119.zippyshare.com/x/xxxxxx/xxxxx/xxxx.rar

real filename and URL omitted.
I generally get 8 megaBYTES per second, which is 64 megabits.  and this is
with no download manager at all. Single segment, bog standard browser
download.

Even with 8 segments, i still can't get quite that fast, though it's
close.  Chrome gets that in ONE.

**Comment by sin2000** [comment]
@zaphod77 
Please send me content of **zdownloader.ini** file.

I have additional questions:
1. Are you using same download folder for zdownloader and Chrome? Are zdownloader and Chrome downloading the file to the same HDD/SDD?
2. What CPU do you have?
3. What is the average CPU usage(in percents) of the zdownloader during the download test?

**Comment by zaphod77** [comment]
1) yes and yes.
2) cpu is Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz   3.00 GHz. i have 8 gig
of ram.
3) 2-3% cpu. 7 megs of ram.  i suspect that chrome is allocating much more
memory than zdownloader is.

my ONLY change from default is max_segments_per_file=1 (i did this because
i wanted to be a good little netizen because my chrome downloads were so
fast, i shouldn't NEED to steal more bandwidth than zippyshare was giving
me.) The legit form of segmented download is downloading same file from
multiple servers.

I noticed that min_segment_size_mb=3, but segment_file_write_buffer_kb=1024. could that be it?

**Comment by zaphod77** [comment]
okay i just bumped up the network read and file write buffers to 8 megs, and now i can get 64Mbps downloads with one segment.

It seems zdownloaders buffer defaults are very conservative.  :)

**Comment by sin2000** [comment]
> okay i just bumped up the network read and file write buffers to 8 megs, and now i can get 64Mbps downloads with one segment.
> 
> It seems zdownloaders buffer defaults are very conservative. :)

I doubt if this is a buffer problem (unless you have very slow HDD/SDD writes like less than 12 MB/s).
I checked myself and it seems that zippyshare limiting dl speed to ~15Mbps when some optional HTTP headers missing.
I didn't notice this before because I have not using application for quite some time.

I have attached(unreleased yet) zdownloader(win7_8_10-x64_beta23.zip) for Windows with some fixes and additional HTTP headers for zippyshare.
**Could you please reset zdownloader.ini to defaults(especially buffers, also set `max_parallel_file_downloads` and `max_segments_per_file` to 1) and check this attached zdownloader?**

Please let me know if you have better download speed with this modified app.

BTW. This probably proves that the zippyshare admin directs his attention to my application. LOL (You aren't zippyshare admin, aren't you? ;) )

[win7_8_10-x64_beta23.zip](https://github.com/sin2000/zdownloader/files/6085310/win7_8_10-x64_beta23.zip)

**Comment by zaphod77** [comment]
no, i'm not zippyshare admin. :) But naturally they don't want you bypassing the popups. So they are not wrong to pull that throttle.  

But right now with the large buffer i'm getting Zippy speeds with 1 segment.

when i had tested today before my buffers change, i was getting 15Mbps with one segment.  But i will test this version after my current downloads finish.

**Comment by zaphod77** [comment]
Okay, tested again with your change. with default buffer settings i get 15Mbps.  While my drives aren't SSDs, they aren't THAT slow.

if i bump the buffers up to 8 megs, i get full speed.  Maybe there's some overhead from the stopping and starting when the network buffer is filled?

Doesn't seem to matter what drive i write to. perhaps it's windows itself causing the issue.  But 2M network and 1M disk buffer is slow, and bumping both to 8 meg is amazingly fast.

**Comment by sin2000** [comment]
I have checked this issue again and you are right that buffers values(`segment_network_read_buffer_kb` and `segment_file_write_buffer_kb`) are too low. So this is not a issue with zippyshare HTTP headers.

**Comment by zaphod77** [comment]
Not sure what the best defaults are for buffers. but i will stick with 8 megabytes (8192), as i am happy with it's speed.
