### ISSUE TITLE
Ignore dead links

### ISSUE THREAD

**Issue by joelbarrette** [sin2000/zdownloader#4]
I've got a large list of links that I'm trying to download but there are some links to zippyshare pages that no longer have the file. Is it possible to bypass that url and keep downloading the rest in that case?

**Comment by sin2000** [comment]
@joelbarrette Could you please check new version of zdownloader:
[https://github.com/sin2000/zdownloader/releases/tag/1.5](https://github.com/sin2000/zdownloader/releases/tag/1.5)

Please **let me know** if zdownloader v1.5 resolves your problem with dead links.
If not please share your applog* messages which shows where the problem occurred.
